[package]
name = "qemer-tui"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-stream = "0.3"
clap = { version = "4.5", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
directories = "6"
futures = "0.3.34"
qemer-answer = { version = "0.1.0", path = "../qemer-answer" }
qemer-core = { version = "0.1.0", path = "../qemer-core" }
ratatui = "0.30.2"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["full"] }
toml = "0.9"
